[package]
name = "morrigu"
version = "0.1.0"
authors = ["Ithyx <lamidey.m@gmail.com>"]
edition = "2021"

[lib]
name = "morrigu"

[dependencies]
log = "0.4"
winit = "0.26"
ash = { version = "0.36", features = ["linked", "debug"] }
ash-window = "0.9"
gpu-allocator = "0.17"
nalgebra-glm = "0.16"

[workspace]
members = [".", "Macha"]

[profile.release]
debug = true
