[package]
name = "morrigu"
version = "0.1.0"
authors = ["Ithyx <lamidey.m@gmail.com>"]
edition = "2021"

[lib]
name = "morrigu"

[dependencies]
log = "0.4"
winit = "0.26"
ash = { version = "0.37", features = ["linked", "debug"] }
ash-window = "0.10"
gpu-allocator = { git = "https://github.com/Ithyx/gpu-allocator", rev = "80c1d98fc58225f4fdf2f9b9d2d8a0fe4c88d90e" }
spirv-reflect = "0.2.3"
nalgebra-glm = "0.16"
image = "0.24.1"
memoffset = "0.6"

[workspace]
members = [".", "Macha"]

[profile.release]
debug = true
