[workspace]
members = [".", "macha"]

[package]
name = "morrigu"
version = "0.1.0"
authors = ["Ithyx <lamidey.m@gmail.com>"]
edition = "2021"

[lib]
name = "morrigu"

[build-dependencies]
shaderc = "0.8"

[dependencies]
log = "0.4"

winit = "0.27"
winit_input_helper = "0.13"
raw-window-handle = "0.5.0"

ash = { version = "0.37", default-features = false, features = [
	"debug",
	"linked",
] }
ash-window = "0.12.0"
gpu-allocator = "0.22"
spirv-reflect = "0.2"

nalgebra = { version = "0.32", features = ["bytemuck"] }
nalgebra-glm = { version = "0.18", features = ["convert-bytemuck"] }

image = "0.24"

memoffset = "0.8.0"
bytemuck = "1.9"

bevy_ecs = "0.9.1"

ply-rs = "0.1"
tobj = "3.2"

egui = { version = "0.20.1", optional = true, features = ["bytemuck"] }
egui-winit = { version = "0.20.1", optional = true }

[features]
egui = ["dep:egui", "dep:egui-winit"]

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
