[package]
name = "morrigu"
version = "0.1.0"
authors = ["Ithyx <lamidey.m@gmail.com>"]
edition = "2021"

[lib]
name = "morrigu"

[build-dependencies]
shaderc = "0.8"

[dependencies]
log = "0.4"

winit = "0.26"
winit_input_helper = "0.12.0"

ash = { version = "0.37", default-features = false, features = [
	"debug",
	"linked",
] }
ash-window = "0.10"
gpu-allocator = { git = "https://github.com/Ithyx/gpu-allocator", rev = "027b89ed49f11e08facb968eea82c58cbb0d5729" }
spirv-reflect = "0.2"

nalgebra = { version = "0.31", features = ["bytemuck"] }
nalgebra-glm = { version = "0.17", features = ["convert-bytemuck"] }

image = "0.24"

memoffset = "0.6"
bytemuck = "1.9"

bevy_ecs = "0.7"

ply-rs = "0.1"
tobj = "3.2"

egui = { version = "0.18", optional = true, features = ["bytemuck"] }
egui-winit = { version = "0.18", optional = true }

[patch.crates-io]
gpu-allocator = { git = "https://github.com/Ithyx/gpu-allocator", rev = "027b89ed49f11e08facb968eea82c58cbb0d5729" }

[workspace]
members = [".", "macha"]

[profile.release]
debug = true

[features]
egui = ["dep:egui", "dep:egui-winit"]
