[package]
name = "morrigu"
version = "0.1.0"
authors = ["Ithyx <lamidey.m@gmail.com>"]
edition = "2021"

[lib]
name = "morrigu"

[dependencies]
log = "0.4.14"
winit = "0.26.1"
ash = { version = "0.35.1", features = ["linked", "debug"] }
ash-window = "0.9.0"

[workspace]
members = [".", "Macha"]
