#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (set = 0, binding = 0, rgba8) uniform readonly image2D inputImage;
layout (set = 0, binding = 1, rgba8) uniform image2D resultImage;

const int blur_diameter = 64;
const int blur_radius = blur_diameter / 2;

void main()
{	
	// Fetch neighbouring texels
    vec3 average = vec3(0.0, 0.0, 0.0);
	for (int i = -(blur_radius - 1); i < blur_radius; ++i) 
	{   
		for(int j = -(blur_radius - 1); j < blur_radius; ++j) 
		{    
			average += (imageLoad(inputImage, ivec2(gl_GlobalInvocationID.x + i, gl_GlobalInvocationID.y + j)).rgb) / float(blur_diameter * blur_diameter);
		}
	}


    imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy), vec4(average, 1.0));
}

