[package]
name = "macha"
version = "0.1.0"
edition = "2021"

[build-dependencies]
shaderc = "0.8.0"

[dependencies]
log = "0.4"
flexi_logger = "0.23"
morrigu = { path = "../", features = ["egui"] }
bevy_ecs = "0.8"
egui = "0.19"
egui-gizmo = "0.7"
winit = "0.27"
winit_input_helper = "0.13"
