[package]
name = "macha"
version = "0.1.0"
edition = "2021"

[build-dependencies]
shaderc = "0.7.4"

[dependencies]
log = "0.4"
flexi_logger = "0.22.3"
morrigu = { path = "../" }
bevy_ecs = "0.7.0"
nalgebra-glm = "0.17.0"
